### ISSUE TITLE
tracePlugin 插桩逻辑有误

### ISSUE THREAD

**Issue by shiqos** [YoungTr/Lancer#1]
https://github.com/YoungTr/Lancer/blob/main/plugin/tracePlugin/src/main/java/com/bomber/strace/TraceMethodVisitor.kt#L7

这里继承AdviceAdapter
只要重写onMethodEnter和onMethodExit
在onMethodEnter中插入Trace.beginSection
onMethodExit中插入Trace.endSection()即可

反编译Demo, 可以看到最终的逻辑

``` 
public class CatchSample {
    public void test() {
        SysTracer.i("com.bomber.strace.sample.CatchSample", "test");
        try {
            System.out.println("try");
        } catch (Exception e) {
            SysTracer.catchIn("com.bomber.strace.sample.CatchSample", "test"); <<---- 1
            e.printStackTrace();
        }
        SysTracer.o("com.bomber.strace.sample.CatchSample", "test"); <<---- 2
    }
}
```

这里 1 和 2 都会执行 Trace.endSection()
这不是我们期望的

可以参考如下链接:
**matrix**

https://github.com/Tencent/matrix/blob/0ee872351b29e78d3b0b192959735a8234c35fa7/matrix/matrix-android/matrix-gradle-plugin/src/main/java/com/tencent/matrix/trace/MethodTracer.java#L370

https://github.com/Tencent/matrix/blob/0ee872351b29e78d3b0b192959735a8234c35fa7/matrix/matrix-android/matrix-gradle-plugin/src/main/java/com/tencent/matrix/trace/MethodTracer.java#L402

**btrace**
https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-gradle-plugin/src/main/java/com/bytedance/rheatrace/plugin/compiling/MethodTracer.kt#L470

https://github.com/bytedance/btrace/blob/master/rhea-build/rhea-gradle-plugin/src/main/java/com/bytedance/rheatrace/plugin/compiling/MethodTracer.kt#L611

**Comment by MRwangqi** [comment]
@saulsq  1 和 2 不会同时执行的哇，1 为了防止 try 代码块中发生了异常，在走 catch 块的时候能走方法闭合，然后整个方法栈就退出了，不会走到方法 2 的地方啊
